def menu_medico():
    print("\n==================== Menu Médico ======================")
    print("1. 🗓️ Ver Consultas")
    print("2. ➕ Adicionar Consulta")
    print("3. 🗓️ Editar Consulta")
    print("4. ❌ Cancelar Consulta")
    print("5. 📋 Visualizar  Pacientes")
    print("6. ➕ Adicionar Pacientes")
    print("7. ➕ Adicionar Diagnóstico")
    print("8. ➕ Adicionar Tratamento")
    print("9. ➕ Adicionar Receita")
    print("10. 📄 Visualizar Receita")
    print("11. 📃 Associar Prontuario")
    print("12. 📃 Visualizar Receita")
    print("13. 🚪 Sair")
    print("=======================================================")
    opcao = input("Escolha uma opção: ")
    return opcao
